server:
  port: 9292
spring:
  datasource:
    password: ZAQ123edc
    username: cms_user
    url: jdbc:mysql://localhost:3306/cms_02
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
        max-file-size: 10MB
myConfig:
    folderPath: /var/www/html/storage/
    folder: /storage/
