server:
  port: 9292
spring:
  datasource:
    password: ZAQ123edc
    username: cms_user
    url: jdbc:mysql://localhost:3306/cms_02
  jpa:
    hibernate:
      ddl-auto: update
myConfig:
    folderPath: /home/tomasz/storage_to_cms/